baseURL = "https://talengu.github.io/"
languageCode = "zh-cn"
title = "一塘"
theme = "hugo-xmin"

[outputs]
home = ["HTML","RSS"]
section = ["HTML","RSS","JSON"]   # 让每个 section 支持 JSON 输出

[params]
  paginate = 10
#  postAssetDir = false
  footer = "&copy; 2025"
  footer_about = "一塘"
  search = true

# 显示文章大纲
[markup]
  [markup.tableOfContents]
    startLevel = 2   # 从 h2 开始生成目录
    endLevel = 4     # 到 h4

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # 允许渲染 HTML（如数学公式）

[menu]
  [[menu.main]]
    identifier = "about"
    name = "一塘"
    url = "/about/"
    weight = 1

  [[menu.main]]
    identifier = "post"
    name = "博客"
    url = "/post/"
    weight = 5

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 20